# Basic Terminologies
---

- **Rank** - Rank of a tensor refers to the number of dimensions present within the tensor. OR How many indices are required to access a specific data element in the tensor.

- **Axes** - It is a specific dimension in the tensor. If, we have a rank-2 tensor then there are two axes or two dimensions. Elements are said to run along an axis. The running is constrained by the length of each axis. The length of the axis tells us how many indices are available to use in order to access data elements. The elements of the last axis is always numbers, every other axis contains nd-array. 
- **Shape** - Shape of tensor is determined by length of each axes. Total indices available along each axis. Length of the shape is the rank of the tensor. Shape incorporates valuable information about the tensor.

In [26]:
import torch
import numpy as np

In [22]:
twoD_tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print("Is is a rank-2 tensor, i.e. two axes or dimensions. Each axis has a length of 3")
print(twoD_tensor)
print(f"Shape is {twoD_tensor.shape}. It means that along each axis how many indices are available.")
print(f"Also rank of a tensor is the length of the shape of tensor. i.e. {len(twoD_tensor.shape)}")

Is is a rank-2 tensor, i.e. two axes or dimensions. Each axis has a length of 3
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape is torch.Size([3, 3]). It means that along each axis how many indices are available.
Also rank of a tensor is the length of the shape of tensor. i.e. 2


## Reshaping tensors.
---
Changes the shape of tensor not the underlying data.

In [23]:
twoD_tensor.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# PyTorch Tensor API

- Tensor computations depend on the data type and device of a tensor.
- 

In [24]:
t = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print("Data type: ", t.dtype)
print("Device where Tensor is stored: ", t.device)
print("How tensor data is laid out in memory: ", t.layout)

Data type:  torch.int64
Device where Tensor is stored:  cpu
How tensor data is laid out in memory:  torch.strided


## Creating Tensors

In [33]:
data = np.array([1,2,3])
t1 = torch.Tensor(data) # Constructor
t2 = torch.tensor(data) # Factory function (Preferred, more customizable)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [35]:
print(torch.eye(2))
print(torch.zeros(2,2))
print(torch.ones(2,2))
print(torch.rand(2,2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.0214, 0.5324],
        [0.3373, 0.6619]])
