# DataLoader and Dataset
---
It is used to create custom datasets. For larger datasets batches are defined for gradient calculation.
- `Epoch` - Forward and backward pass of all the training samples.
- `batch_size` - Number of training samples in one forward and backward pass.
- `num_of_iterations` - Number of passes, each pass using [batch_size] number of samples.
E.g - 100 samples with batch_size = 20, then 100/20 = 5 iterations for 1 epoch.

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
from math import ceil
torch.__version__

'1.4.0'

In [2]:
class WineDataset(Dataset):
    def __init__(self):
        # Data loading
        xy = np.loadtxt('wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]])
        self.n_samples = xy.shape[0]
    def __getitem__(self, index):
        # return the item at a specific index
        return self.x[index], self.y[index]
    def __len__(self):
        # Length of the dataset
        return self.n_samples

In [3]:
# Create the dataset object and view the fifth object.
dataset = WineDataset()
feature_1, label_1 = dataset[5]
print(f"Fifth Data point features:\n{feature_1}\nFifth data point label:\n{label_1}")

Fifth Data point features:
tensor([1.4200e+01, 1.7600e+00, 2.4500e+00, 1.5200e+01, 1.1200e+02, 3.2700e+00,
        3.3900e+00, 3.4000e-01, 1.9700e+00, 6.7500e+00, 1.0500e+00, 2.8500e+00,
        1.4500e+03])
Fifth data point label:
tensor([1.])


In [4]:
# Load the data
dataloader = DataLoader(dataset=dataset, batch_size=5, shuffle=True, num_workers=2)
data_iter = iter(dataloader)
data = data_iter.next()
features, labels = data
print(features, labels)
print("Since the batch size is 5, we have 5 data points in one iter.")

tensor([[1.3050e+01, 1.7300e+00, 2.0400e+00, 1.2400e+01, 9.2000e+01, 2.7200e+00,
         3.2700e+00, 1.7000e-01, 2.9100e+00, 7.2000e+00, 1.1200e+00, 2.9100e+00,
         1.1500e+03],
        [1.3080e+01, 3.9000e+00, 2.3600e+00, 2.1500e+01, 1.1300e+02, 1.4100e+00,
         1.3900e+00, 3.4000e-01, 1.1400e+00, 9.4000e+00, 5.7000e-01, 1.3300e+00,
         5.5000e+02],
        [1.3630e+01, 1.8100e+00, 2.7000e+00, 1.7200e+01, 1.1200e+02, 2.8500e+00,
         2.9100e+00, 3.0000e-01, 1.4600e+00, 7.3000e+00, 1.2800e+00, 2.8800e+00,
         1.3100e+03],
        [1.2530e+01, 5.5100e+00, 2.6400e+00, 2.5000e+01, 9.6000e+01, 1.7900e+00,
         6.0000e-01, 6.3000e-01, 1.1000e+00, 5.0000e+00, 8.2000e-01, 1.6900e+00,
         5.1500e+02],
        [1.2770e+01, 3.4300e+00, 1.9800e+00, 1.6000e+01, 8.0000e+01, 1.6300e+00,
         1.2500e+00, 4.3000e-01, 8.3000e-01, 3.4000e+00, 7.0000e-01, 2.1200e+00,
         3.7200e+02]]) tensor([[1.],
        [3.],
        [1.],
        [3.],
        [2.]])
Since th

In [5]:
# Hyperparameters
epochs = 2
batch_size = 5
total_samples = len(dataset)
num_of_iterations = ceil(total_samples / batch_size)
print(f"Batch Size: {batch_size}")
print(f"Total Samples: {total_samples}")
print(f"Number of iterations: {num_of_iterations}")

Batch Size: 5
Total Samples: 178
Number of iterations: 36


In [8]:
# Training loop
for epoch in range(epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        # Forward pass
        if (i+1) % 6 == 0:
            print(f"Epoch: {epoch+1}/{epochs}, Step: {i+1}/{num_of_iterations}, Input Shape: {inputs.shape}")
print("2 Epochs with 36 iterations each, with batch size of 5, with 13 features.")

Epoch: 1/2, Step: 6/36, Input Shape: torch.Size([5, 13])
Epoch: 1/2, Step: 12/36, Input Shape: torch.Size([5, 13])
Epoch: 1/2, Step: 18/36, Input Shape: torch.Size([5, 13])
Epoch: 1/2, Step: 24/36, Input Shape: torch.Size([5, 13])
Epoch: 1/2, Step: 30/36, Input Shape: torch.Size([5, 13])
Epoch: 1/2, Step: 36/36, Input Shape: torch.Size([3, 13])
Epoch: 2/2, Step: 6/36, Input Shape: torch.Size([5, 13])
Epoch: 2/2, Step: 12/36, Input Shape: torch.Size([5, 13])
Epoch: 2/2, Step: 18/36, Input Shape: torch.Size([5, 13])
Epoch: 2/2, Step: 24/36, Input Shape: torch.Size([5, 13])
Epoch: 2/2, Step: 30/36, Input Shape: torch.Size([5, 13])
Epoch: 2/2, Step: 36/36, Input Shape: torch.Size([3, 13])
2 Epochs with 36 iterations each, with batch size of 5, with 13 features.
